/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rollerCoverElisa.glb -t 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Line001: THREE.Mesh;
    Line004: THREE.Mesh;
    Line008: THREE.Mesh;
    Line009: THREE.Mesh;
    Line010: THREE.Mesh;
    Line011: THREE.Mesh;
    Line012: THREE.Mesh;
    Line013: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Plane: THREE.Mesh;
    Line009001: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube011: THREE.Mesh;
    Plane001: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
  };
};

export function RollerCoverElisa(
  props: JSX.IntrinsicElements["group"] & { lineColor?: string }
) {
  const { nodes, materials, scene } = useGLTF(
    "/rollerCoverElisa.glb"
  ) as GLTFResult;

  useEffect(() => {
    scene.children.map((e) =>
      (e as THREE.Mesh).geometry.computeVertexNormals()
    );
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Line001.geometry}
        material={materials.material}
        material-color={props.lineColor}
        position={[-0.079, 0.024, 0.004]}
        scale={[1, 0.369, 1]}
      />
      <mesh
        geometry={nodes.Line004.geometry}
        material={materials.material}
        position={[0, 0, 0.019]}
      />
      <mesh
        geometry={nodes.Line008.geometry}
        material={materials.material}
        position={[0, 0.036, 1.031]}
      />
      <mesh
        geometry={nodes.Line009.geometry}
        material={materials.material}
        position={[0, 0, 0.715]}
      />
      <mesh geometry={nodes.Line010.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Line011.geometry}
        material={materials.material}
        position={[0, 0, 0.389]}
      />
      <mesh
        geometry={nodes.Line012.geometry}
        material={materials.material}
        position={[-0.038, 0.012, 1.735]}
        scale={[1, 0.369, 1]}
      />
      <mesh
        geometry={nodes.Line013.geometry}
        material={materials.material}
        position={[-0.038, 0.012, -1.768]}
        scale={[1, 0.369, 1]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.material}
        position={[-0.606, 0.255, 1.267]}
      />
      <mesh geometry={nodes.Cube050.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.material}
        position={[0.054, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.material}
        position={[0.21, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.material}
        position={[0.359, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.material}
        position={[0.507, 0.255, 1.287]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.material}
        position={[-0.45, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.material}
        position={[-0.301, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.material}
        position={[-0.153, 0.255, 1.267]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Glass}
        position={[-0.285, 0.015, 1.72]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line009001.geometry}
        material={materials.material}
        position={[0, 0, 1.559]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.material}
        position={[-0.153, 0.046, 1.184]}
        scale={[1, 1, 1.02]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.material}
        position={[-0.004, 0.046, 1.184]}
        scale={[1, 1, 1.02]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.material}
        position={[-0.301, 0.046, 1.182]}
        scale={[1, 1, 1.02]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.material}
        position={[-0.457, 0.046, 1.182]}
        scale={[1, 1, 1.02]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Glass}
        position={[-0.797, 0.047, 0.294]}
        rotation={[0, 0, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/rollerCoverElisa.glb");
