/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rollerCoverBlack.glb -t 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Collar: THREE.Mesh;
    Line001: THREE.Mesh;
    Line002: THREE.Mesh;
    Line003: THREE.Mesh;
    Line005: THREE.Mesh;
    Support001: THREE.Mesh;
    Suppoort002: THREE.Mesh;
    center: THREE.Mesh;
    Glass003: THREE.Mesh;
    Line003001: THREE.Mesh;
    Line003002: THREE.Mesh;
    Glass001: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Collar001: THREE.Mesh;
    Line003003: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube032: THREE.Mesh;
  };
  materials: {
    metal: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    ["metal.002"]: THREE.MeshStandardMaterial;
    ["metal.003"]: THREE.MeshStandardMaterial;
    ["metal.001"]: THREE.MeshStandardMaterial;
  };
};

export function RollerCoverBlack(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials, scene } = useGLTF(
    "/rollerCoverBlack.glb"
  ) as GLTFResult;
  useEffect(() => {
    scene.children.map((e) =>
      (e as THREE.Mesh).geometry.computeVertexNormals()
    );
  }, [scene]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Collar.geometry}
        material={materials.metal}
        position={[-0.078, 0.019, 0.004]}
      />
      <mesh
        geometry={nodes.Line001.geometry}
        material={materials.metal}
        position={[-0.097, 0.12, 1.698]}
      />
      <mesh
        geometry={nodes.Line002.geometry}
        material={materials.metal}
        position={[-0.097, 0.12, 0.95]}
      />
      <mesh
        geometry={nodes.Line003.geometry}
        material={materials.metal}
        position={[-0.097, 0.12, 0.052]}
      />
      <mesh
        geometry={nodes.Line005.geometry}
        material={materials.metal}
        position={[-0.071, 0.123, -1.732]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.025, 0.025, 0.009]}
      />
      <mesh
        geometry={nodes.Support001.geometry}
        material={materials.metal}
        position={[-0.036, 0.006, 1.735]}
      />
      <mesh
        geometry={nodes.Suppoort002.geometry}
        material={materials.metal}
        position={[-0.036, 0.006, -1.736]}
      />
      <mesh
        geometry={nodes.center.geometry}
        material={materials.metal}
        position={[-0.002, 0.105, 0.135]}
      />
      <mesh
        geometry={nodes.Glass003.geometry}
        material={materials.Glass}
        position={[-0.053, 0.095, -2.229]}
      />
      <mesh
        geometry={nodes.Line003001.geometry}
        material={materials.metal}
        position={[-0.097, 0.12, -0.85]}
      />
      <mesh
        geometry={nodes.Line003002.geometry}
        material={materials.metal}
        position={[-0.056, 0.161, 0.052]}
      />
      <mesh
        geometry={nodes.Glass001.geometry}
        material={materials.Glass}
        position={[0.413, -0.851, -2.411]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.metal}
        position={[0.551, 0.348, -0.399]}
        rotation={[-3.137, 0.001, -0.001]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.metal}
        position={[0.402, 0.365, -0.399]}
        rotation={[-3.137, 0.001, -0.001]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.metal}
        position={[0.251, 0.378, -0.399]}
        rotation={[-3.137, 0.001, -0.001]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.metal}
        position={[0.109, 0.384, -0.399]}
        rotation={[-3.137, 0.001, -0.001]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Collar001.geometry}
        material={materials["metal.002"]}
        position={[-0.078, 0.019, 0.004]}
      />
      <mesh
        geometry={nodes.Line003003.geometry}
        material={materials["metal.003"]}
        position={[-0.056, 0.161, 0.052]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["metal.001"]}
        position={[0.551, 0.251, -0.42]}
        rotation={[-3.137, 0.002, 0.134]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["metal.001"]}
        position={[0.401, 0.268, -0.42]}
        rotation={[-3.137, 0.001, 0.084]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["metal.001"]}
        position={[0.248, 0.281, -0.42]}
        rotation={[-3.137, 0.001, 0.075]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["metal.001"]}
        position={[0.109, 0.286, -0.42]}
        rotation={[-3.137, 0.001, 0.026]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["metal.001"]}
        position={[0.551, 0.188, 0.478]}
        rotation={[-3.137, 0.002, 0.134]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["metal.001"]}
        position={[0.401, 0.205, 0.478]}
        rotation={[-3.137, 0.001, 0.084]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["metal.001"]}
        position={[0.248, 0.218, 0.478]}
        rotation={[-3.137, 0.001, 0.075]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["metal.001"]}
        position={[0.109, 0.223, 0.478]}
        rotation={[-3.137, 0.001, 0.026]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["metal.001"]}
        position={[0.551, 0.132, 1.227]}
        rotation={[-3.137, 0.002, 0.134]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["metal.001"]}
        position={[0.401, 0.148, 1.227]}
        rotation={[-3.137, 0.001, 0.084]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["metal.001"]}
        position={[0.248, 0.162, 1.227]}
        rotation={[-3.137, 0.001, 0.075]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials["metal.001"]}
        position={[0.109, 0.166, 1.227]}
        rotation={[-3.137, 0.001, 0.026]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["metal.001"]}
        position={[-0.158, 0.285, -0.42]}
        rotation={[-3.137, 0.001, -0.027]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["metal.001"]}
        position={[-0.309, 0.277, -0.42]}
        rotation={[-3.137, 0.001, -0.053]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["metal.001"]}
        position={[-0.46, 0.267, -0.42]}
        rotation={[-3.137, 0.001, -0.071]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials["metal.001"]}
        position={[-0.599, 0.255, -0.418]}
        rotation={[-3.137, 0.001, -0.08]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["metal.001"]}
        position={[-0.158, 0.342, -1.285]}
        rotation={[-3.137, 0.001, -0.027]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["metal.001"]}
        position={[-0.309, 0.334, -1.285]}
        rotation={[-3.137, 0.001, -0.053]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["metal.001"]}
        position={[-0.46, 0.324, -1.285]}
        rotation={[-3.137, 0.001, -0.071]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["metal.001"]}
        position={[-0.599, 0.312, -1.284]}
        rotation={[-3.137, 0.001, -0.08]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials["metal.001"]}
        position={[-0.158, 0.222, 0.478]}
        rotation={[-3.137, 0.001, -0.027]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["metal.001"]}
        position={[-0.309, 0.214, 0.478]}
        rotation={[-3.137, 0.001, -0.053]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["metal.001"]}
        position={[-0.46, 0.204, 0.478]}
        rotation={[-3.137, 0.001, -0.071]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials["metal.001"]}
        position={[-0.599, 0.192, 0.48]}
        rotation={[-3.137, 0.001, -0.08]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials["metal.001"]}
        position={[-0.158, 0.166, 1.227]}
        rotation={[-3.137, 0.001, -0.027]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials["metal.001"]}
        position={[-0.309, 0.158, 1.227]}
        rotation={[-3.137, 0.001, -0.053]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["metal.001"]}
        position={[-0.46, 0.148, 1.227]}
        rotation={[-3.137, 0.001, -0.071]}
        scale={[-0.008, -0.007, -0.221]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials["metal.001"]}
        position={[-0.599, 0.136, 1.229]}
        rotation={[-3.137, 0.001, -0.08]}
        scale={[-0.008, -0.007, -0.221]}
      />
    </group>
  );
}

useGLTF.preload("/rollerCoverBlack.glb");
